In [26]:
import pandas as pd
import numpy as np
from plotly import __version__
import plotly.express as px
print(__version__)

4.14.3

In [27]:
import cufflinks as cf
from plotly.offline import download_plotlyjs,init_notebook_mode,plot,iplot

In [28]:

init_notebook_mode(connected=True)

In [29]:

cf.go_offline()

In [30]:
#Data
df=np.random.randn(100,4)

In [31]:
df

array([[ 1.45065752e-01, -1.44655712e+00,  1.69850709e+00,
         3.72247684e-01],
       [-6.75722709e-01,  9.72726002e-01,  2.70690856e-01,
         1.42031883e+00],
       [-9.98921357e-01, -1.24134971e+00,  1.12853676e+00,
         1.20145859e+00],
       [ 2.08816401e+00, -3.47269588e-01, -1.83685214e+00,
        -1.37106518e-01],
       [-3.65849396e-01, -1.98930010e-03, -1.27633910e+00,
        -1.24304266e+00],
       [ 5.42007340e-01,  1.51465990e-01, -6.04877772e-01,
        -5.95515991e-01],
       [ 1.24810638e+00, -1.88631581e+00, -2.11218754e-01,
        -4.74432938e-01],
       [ 1.85444568e-01,  8.34431549e-01, -1.59293510e-01,
        -4.49137270e-01],
       [-8.90165365e-01, -9.04122671e-02,  7.61465162e-01,
         5.70241844e-01],
       [ 1.87744459e+00, -2.92617468e-01,  3.88439844e-02,
         1.72277462e+00],
       [ 9.50470888e-01, -1.09140888e+00, -3.14698362e-01,
        -1.96898723e+00],
       [-2.97592661e-01,  2.31749627e+00,  1.26781263e+00,
        -8.02300265e-01],
       [-1.78083362e-02,  1.68964087e+00, -1.45712123e-01,
        -7.11947098e-01],
       [ 9.29781803e-02,  1.04171513e+00,  9.25248889e-01,
         1.87827642e-01],
       [ 4.08354999e-01, -1.07103020e+00, -7.86868913e-01,
         1.23496253e+00],
       [-3.35736419e-01,  3.29756341e-01, -3.75964413e-01,
         4.96844877e-01],
       [-3.93405523e-01,  1.11344636e-01,  8.86985728e-01,
         1.96656963e-01],
       [ 6.24149772e-02, -5.96000547e-02, -6.18890620e-01,
        -6.86593462e-01],
       [-3.39086827e-02,  1.11855027e+00, -6.56806745e-01,
         9.88513266e-01],
       [ 1.07040321e+00,  1.09718149e+00, -2.47635719e-01,
        -4.73908302e-01],
       [-1.57626939e-01,  8.87089607e-01,  6.68524298e-01,
        -2.05632997e-02],
       [ 3.36648935e-01,  1.69334650e+00, -5.93797080e-02,
         5.95348795e-01],
       [-1.08626924e+00,  1.21597888e+00,  5.07663363e-01,
        -1.89123038e+00],
       [-3.70795219e-01,  1.44117684e+00,  7.86315791e-01,
        -1.63406254e+00],
       [ 1.67790391e+00,  1.51203667e+00,  1.55621247e+00,
         5.06444792e-01],
       [ 1.83210132e+00, -3.15675215e-01,  2.83940090e-01,
         6.09806490e-01],
       [ 4.10215221e-01,  9.87311434e-01,  1.13758868e+00,
         9.21818541e-02],
       [-7.82510914e-01, -6.07257105e-01, -6.93240862e-01,
         3.90385815e-01],
       [-1.81049466e-01, -1.38805098e+00,  1.56623124e+00,
         5.92636000e-01],
       [ 3.37091519e-01,  1.00763907e+00,  1.84923994e-01,
         5.41031512e-01],
       [ 9.24015786e-01,  1.30947806e+00, -3.42239206e-01,
        -5.32127774e-02],
       [-4.24564443e-01, -5.47399027e-01, -5.02598607e-01,
         1.16959740e-01],
       [-7.69865055e-01,  7.07942033e-01,  7.22998565e-01,
        -1.09955590e+00],
       [-7.86665941e-01, -3.70994427e-01,  1.80175895e-01,
         1.04321110e+00],
       [ 6.44524501e-01,  1.79832931e+00, -2.30088241e-01,
         1.57891527e+00],
       [ 6.32017851e-01,  1.63970540e+00,  6.85618972e-01,
        -7.72665304e-01],
       [ 1.97362786e-01,  8.17643999e-01,  8.38460950e-01,
        -1.49764639e+00],
       [-4.43552390e-01,  4.92185095e-01,  5.77836883e-01,
        -1.38495994e+00],
       [-1.68813288e-01,  5.27586719e-01, -3.16367075e-01,
         3.61185316e-01],
       [ 2.07267192e-01, -1.02509673e-01, -3.24692027e-02,
         5.90798317e-01],
       [ 2.99497223e-01, -1.30991379e+00,  3.61017660e-01,
         9.33423956e-01],
       [ 6.03266040e-01,  9.45557814e-02, -8.28194042e-01,
        -4.02486140e-01],
       [ 8.55924452e-01, -3.98362299e-01, -5.55484544e-01,
         9.31164417e-01],
       [ 1.33267784e-02,  6.40416677e-01, -8.27606854e-01,
        -7.70782338e-01],
       [-7.97134427e-01,  3.76633881e-01,  1.53580719e+00,
         5.87404253e-02],
       [ 1.02237120e+00,  2.46435541e-01, -6.36632081e-02,
        -2.04532625e+00],
       [ 1.47914545e-01, -2.32722529e+00,  1.11802888e-01,
         2.07453852e-02],
       [-1.00742210e+00,  1.65080086e+00,  2.19065625e-01,
        -9.68246281e-01],
       [-7.95524772e-01,  1.80369395e+00, -1.01426638e+00,
        -2.24102243e+00],
       [ 2.03230540e+00,  7.88190408e-01,  1.05566540e+00,
         4.29321296e-01],
       [ 1.85771877e+00, -8.72279041e-01,  7.33660738e-01,
        -6.68652166e-01],
       [ 1.26285840e-01, -9.16353730e-01, -6.04658352e-01,
        -3.58876241e-01],
       [-3.76940281e-01, -2.87610466e-01,  7.39434151e-01,
        -5.84569677e-01],
       [-7.57986047e-01,  1.49119000e+00,  7.76672857e-01,
         1.07268687e+00],
       [ 1.33695997e+00, -2.27686238e+00, -4.75177759e-01,
        -7.52380889e-01],
       [ 7.77389039e-01, -5.05690294e-01,  9.27094149e-01,
         1.14223055e+00],
       [ 2.20402015e-01, -1.74155189e+00, -1.26453845e-01,
         1.39637720e+00],
       [-3.77295346e-01,  3.54482257e-01, -2.15211291e-01,
        -2.75386844e-01],
       [ 2.53424302e+00, -6.96992553e-01, -1.83724353e+00,
        -3.59065495e-01],
       [ 4.16949146e-01, -6.85582533e-01,  7.88825659e-01,
         1.17721136e+00],
       [ 4.51021160e-01, -1.33129924e+00,  2.15871719e-01,
        -8.43130048e-01],
       [-6.05130790e-01,  4.57906095e-01, -1.71577722e-01,
         1.67870319e+00],
       [-1.63316094e+00, -6.69966242e-01,  1.50027605e+00,
        -8.12768934e-01],
       [-6.49536842e-01, -2.34568692e-01, -1.10875354e+00,
        -2.56163202e+00],
       [-1.47976810e+00,  4.54011879e-01,  6.48638624e-01,
        -6.62402283e-01],
       [ 9.09539459e-01, -7.37891410e-01, -1.00673828e+00,
         9.96427980e-01],
       [-1.60318758e+00,  6.42415550e-01, -1.85278395e+00,
         3.85783179e-01],
       [ 7.53764911e-01,  1.83414928e-01, -7.70274698e-01,
        -1.09414400e-01],
       [-7.13161789e-01, -1.01986521e+00,  2.54195298e-01,
        -1.84387387e+00],
       [-2.17576321e+00, -1.14294198e+00, -2.27332699e+00,
        -1.44564880e+00],
       [-5.66449469e-01,  4.75782370e-01,  1.55276775e+00,
         1.12830642e+00],
       [ 5.98296421e-01, -9.52937883e-02, -1.03912844e+00,
         1.10514920e-01],
       [-1.90020077e+00, -8.89158131e-02, -8.55199588e-01,
        -2.39278362e-01],
       [ 4.80840125e-02, -3.69274774e-01, -1.48671939e+00,
         1.33369869e+00],
       [-6.93024005e-01,  7.75262378e-01, -3.68327790e-01,
         1.36240833e+00],
       [-6.06245773e-01,  4.67883856e-01, -1.00418207e-01,
        -3.02637020e-01],
       [ 3.86224274e-01, -6.87042579e-01, -1.06109314e+00,
        -1.57534922e+00],
       [-1.21833984e+00,  8.39624870e-01,  2.14592078e-01,
        -1.43985015e+00],
       [-3.02082820e-01,  5.79733597e-01, -6.16850176e-01,
         8.44337196e-01],
       [-3.62618004e-01, -2.41187040e-01,  1.11681740e+00,
        -7.68735995e-01],
       [-1.47225121e+00,  1.37524920e+00, -1.09579575e+00,
        -4.63811073e-01],
       [ 1.42969437e+00,  5.15345831e-01, -1.13568893e-01,
         2.40341388e+00],
       [ 1.68839554e+00, -6.72060906e-01,  5.25601537e-01,
        -7.52677203e-01],
       [-1.77540492e+00, -1.41710748e+00, -1.80472652e+00,
         2.01974804e-01],
       [-1.85476070e+00, -1.73421291e-01,  8.30513993e-01,
         1.30612856e+00],
       [-1.89348567e+00, -6.69558281e-01, -2.33192067e+00,
         2.85276527e-01],
       [ 8.01756682e-01,  1.20974516e+00, -7.22453628e-01,
        -2.15310362e-01],
       [ 8.02645714e-01,  2.14555233e-01,  1.00046739e+00,
         1.50493799e+00],
       [-5.04437559e-02,  8.95852100e-01, -1.48230876e+00,
        -9.17964810e-02],
       [-1.30884241e+00,  1.33424912e+00, -1.27476812e-01,
         4.66710898e-01],
       [-1.23909020e+00,  3.55738918e-01, -1.07854871e+00,
        -5.12974863e-01],
       [ 2.16926557e+00,  8.99757019e-01,  4.64263778e-01,
         9.84603299e-01],
       [ 6.06226780e-01,  7.62010717e-04,  1.33390719e-01,
         2.30606681e-01],
       [ 1.24016354e+00,  1.68224999e+00, -1.79157246e+00,
        -1.14335029e+00],
       [-1.42279253e+00, -1.04993628e+00,  2.71399530e+00,
        -1.00601480e+00],
       [ 2.00411457e+00,  1.80112328e+00, -1.32199221e+00,
        -1.14123362e+00],
       [-2.44114611e+00, -2.92413657e+00, -1.34195848e-01,
        -1.13696766e+00],
       [-5.13827453e-01,  8.12158966e-02,  1.99544553e-02,
        -6.06876278e-01],
       [-4.71746774e-01,  5.82691502e-01,  1.48859986e+00,
         1.81555913e+00],
       [-2.47853795e-01, -2.89114757e-01, -1.18550467e+00,
        -1.47814133e+00]])

In [32]:
df=pd.DataFrame(df,columns="A B C D".split())

In [33]:
df

           A         B         C         D
0   0.145066 -1.446557  1.698507  0.372248
1  -0.675723  0.972726  0.270691  1.420319
2  -0.998921 -1.241350  1.128537  1.201459
3   2.088164 -0.347270 -1.836852 -0.137107
4  -0.365849 -0.001989 -1.276339 -1.243043
..       ...       ...       ...       ...
95  2.004115  1.801123 -1.321992 -1.141234
96 -2.441146 -2.924137 -0.134196 -1.136968
97 -0.513827  0.081216  0.019954 -0.606876
98 -0.471747  0.582692  1.488600  1.815559
99 -0.247854 -0.289115 -1.185505 -1.478141

[100 rows x 4 columns]

In [34]:
df2=pd.DataFrame({'Category':['A' ,'B', 'C', 'D'],"Values":[32,21,45,13]})
df2

  Category  Values
0        A      32
1        B      21
2        C      45
3        D      13

In [35]:
fig=px.histogram(df)
fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'alignmentgroup': 'True',
              'bingroup': 'x',
              'hovertemplate': 'variable=A<br>value=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'A',
              'marker': {'color': '#636efa'},
              'name': 'A',
              'offsetgroup': 'A',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': array([ 0.14506575, -0.67572271, -0.99892136,  2.08816401, -0.3658494 ,
                           0.54200734,  1.24810638,  0.18544457, -0.89016536,  1.87744459,
                           0.95047089, -0.29759266, -0.01780834,  0.09297818,  0.408355  ,
                          -0.33573642, -0.39340552,  0.06241498, -0.03390868,  1.07040321,
                          -0.15762694,  0.33664893, -1.08626924, -0.37079522,  1.67790391,
                           1.83210132,  0.41021522, -0.78251091, -0.18104947,  0.33709152,
                           0.92401579, -0.42456444, -0.76986506, -0.78666594,  0.6445245 ,
                           0.63201785,  0.19736279, -0.44355239, -0.16881329,  0.20726719,
                           0.29949722,  0.60326604,  0.85592445,  0.01332678, -0.79713443,
                           1.0223712 ,  0.14791455, -1.0074221 , -0.79552477,  2.0323054 ,
                           1.85771877,  0.12628584, -0.37694028, -0.75798605,  1.33695997,
                           0.77738904,  0.22040202, -0.37729535,  2.53424302,  0.41694915,
                           0.45102116, -0.60513079, -1.63316094, -0.64953684, -1.4797681 ,
                           0.90953946, -1.60318758,  0.75376491, -0.71316179, -2.17576321,
                          -0.56644947,  0.59829642, -1.90020077,  0.04808401, -0.693024  ,
                          -0.60624577,  0.38622427, -1.21833984, -0.30208282, -0.362618  ,
                          -1.47225121,  1.42969437,  1.68839554, -1.77540492, -1.8547607 ,
                          -1.89348567,  0.80175668,  0.80264571, -0.05044376, -1.30884241,
                          -1.2390902 ,  2.16926557,  0.60622678,  1.24016354, -1.42279253,
                           2.00411457, -2.44114611, -0.51382745, -0.47174677, -0.2478538 ]),
              'xaxis': 'x',
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'bingroup': 'x',
              'hovertemplate': 'variable=B<br>value=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'B',
              'marker': {'color': '#EF553B'},
              'name': 'B',
              'offsetgroup': 'B',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': array([-1.44655712e+00,  9.72726002e-01, -1.24134971e+00, -3.47269588e-01,
                          -1.98930010e-03,  1.51465990e-01, -1.88631581e+00,  8.34431549e-01,
                          -9.04122671e-02, -2.92617468e-01, -1.09140888e+00,  2.31749627e+00,
                           1.68964087e+00,  1.04171513e+00, -1.07103020e+00,  3.29756341e-01,
                           1.11344636e-01, -5.96000547e-02,  1.11855027e+00,  1.09718149e+00,
                           8.87089607e-01,  1.69334650e+00,  1.21597888e+00,  1.44117684e+00,
                           1.51203667e+00, -3.15675215e-01,  9.87311434e-01, -6.07257105e-01,
                          -1.38805098e+00,  1.00763907e+00,  1.30947806e+00, -5.47399027e-01,
                           7.07942033e-01, -3.70994427e-01,  1.79832931e+00,  1.63970540e+00,
                           8.17643999e-01,  4.92185095e-01,  5.27586719e-01, -1.02509673e-01,
                          -1.30991379e+00,  9.45557814e-02, -3.98362299e-01,  6.40416677e-01,
                           3.76633881e-01,  2.46435541e-01, -2.32722529e+00,  1.65080086e+00,
                           1.80369395e+00,  7.88190408e-01, -8.72279041e-01, -9.16353730e-01,
                          -2.87610466e-01,  1.49119000e+00, -2.27686238e+00, -5.05690294e-01,
                          -1.74155189e+00,  3.54482257e-01, -6.96992553e-01, -6.85582533e-01,
                          -1.33129924e+00,  4.57906095e-01, -6.69966242e-01, -2.34568692e-01,
                           4.54011879e-01, -7.37891410e-01,  6.42415550e-01,  1.83414928e-01,
                          -1.01986521e+00, -1.14294198e+00,  4.75782370e-01, -9.52937883e-02,
                          -8.89158131e-02, -3.69274774e-01,  7.75262378e-01,  4.67883856e-01,
                          -6.87042579e-01,  8.39624870e-01,  5.79733597e-01, -2.41187040e-01,
                           1.37524920e+00,  5.15345831e-01, -6.72060906e-01, -1.41710748e+00,
                          -1.73421291e-01, -6.69558281e-01,  1.20974516e+00,  2.14555233e-01,
                           8.95852100e-01,  1.33424912e+00,  3.55738918e-01,  8.99757019e-01,
                           7.62010717e-04,  1.68224999e+00, -1.04993628e+00,  1.80112328e+00,
                          -2.92413657e+00,  8.12158966e-02,  5.82691502e-01, -2.89114757e-01]),
              'xaxis': 'x',
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'bingroup': 'x',
              'hovertemplate': 'variable=C<br>value=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'C',
              'marker': {'color': '#00cc96'},
              'name': 'C',
              'offsetgroup': 'C',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': array([ 1.69850709,  0.27069086,  1.12853676, -1.83685214, -1.2763391 ,
                          -0.60487777, -0.21121875, -0.15929351,  0.76146516,  0.03884398,
                          -0.31469836,  1.26781263, -0.14571212,  0.92524889, -0.78686891,
                          -0.37596441,  0.88698573, -0.61889062, -0.65680675, -0.24763572,
                           0.6685243 , -0.05937971,  0.50766336,  0.78631579,  1.55621247,
                           0.28394009,  1.13758868, -0.69324086,  1.56623124,  0.18492399,
                          -0.34223921, -0.50259861,  0.72299857,  0.1801759 , -0.23008824,
                           0.68561897,  0.83846095,  0.57783688, -0.31636708, -0.0324692 ,
                           0.36101766, -0.82819404, -0.55548454, -0.82760685,  1.53580719,
                          -0.06366321,  0.11180289,  0.21906562, -1.01426638,  1.0556654 ,
                           0.73366074, -0.60465835,  0.73943415,  0.77667286, -0.47517776,
                           0.92709415, -0.12645384, -0.21521129, -1.83724353,  0.78882566,
                           0.21587172, -0.17157772,  1.50027605, -1.10875354,  0.64863862,
                          -1.00673828, -1.85278395, -0.7702747 ,  0.2541953 , -2.27332699,
                           1.55276775, -1.03912844, -0.85519959, -1.48671939, -0.36832779,
                          -0.10041821, -1.06109314,  0.21459208, -0.61685018,  1.1168174 ,
                          -1.09579575, -0.11356889,  0.52560154, -1.80472652,  0.83051399,
                          -2.33192067, -0.72245363,  1.00046739, -1.48230876, -0.12747681,
                          -1.07854871,  0.46426378,  0.13339072, -1.79157246,  2.7139953 ,
                          -1.32199221, -0.13419585,  0.01995446,  1.48859986, -1.18550467]),
              'xaxis': 'x',
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'bingroup': 'x',
              'hovertemplate': 'variable=D<br>value=%{x}<br>count=%{y}<extra></extra>',
              'legendgroup': 'D',
              'marker': {'color': '#ab63fa'},
              'name': 'D',
              'offsetgroup': 'D',
              'orientation': 'v',
              'showlegend': True,
              'type': 'histogram',
              'x': array([ 0.37224768,  1.42031883,  1.20145859, -0.13710652, -1.24304266,
                          -0.59551599, -0.47443294, -0.44913727,  0.57024184,  1.72277462,
                          -1.96898723, -0.80230027, -0.7119471 ,  0.18782764,  1.23496253,
                           0.49684488,  0.19665696, -0.68659346,  0.98851327, -0.4739083 ,
                          -0.0205633 ,  0.59534879, -1.89123038, -1.63406254,  0.50644479,
                           0.60980649,  0.09218185,  0.39038581,  0.592636  ,  0.54103151,
                          -0.05321278,  0.11695974, -1.0995559 ,  1.0432111 ,  1.57891527,
                          -0.7726653 , -1.49764639, -1.38495994,  0.36118532,  0.59079832,
                           0.93342396, -0.40248614,  0.93116442, -0.77078234,  0.05874043,
                          -2.04532625,  0.02074539, -0.96824628, -2.24102243,  0.4293213 ,
                          -0.66865217, -0.35887624, -0.58456968,  1.07268687, -0.75238089,
                           1.14223055,  1.3963772 , -0.27538684, -0.3590655 ,  1.17721136,
                          -0.84313005,  1.67870319, -0.81276893, -2.56163202, -0.66240228,
                           0.99642798,  0.38578318, -0.1094144 , -1.84387387, -1.4456488 ,
                           1.12830642,  0.11051492, -0.23927836,  1.33369869,  1.36240833,
                          -0.30263702, -1.57534922, -1.43985015,  0.8443372 , -0.76873599,
                          -0.46381107,  2.40341388, -0.7526772 ,  0.2019748 ,  1.30612856,
                           0.28527653, -0.21531036,  1.50493799, -0.09179648,  0.4667109 ,
                          -0.51297486,  0.9846033 ,  0.23060668, -1.14335029, -1.0060148 ,
                          -1.14123362, -1.13696766, -0.60687628,  1.81555913, -1.47814133]),
              'xaxis': 'x',
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'variable'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'value'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'count'}}}
})

In [36]:
fig1=px.bar(df)
fig1

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'alignmentgroup': 'True',
              'hovertemplate': 'variable=A<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'A',
              'marker': {'color': '#636efa'},
              'name': 'A',
              'offsetgroup': 'A',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
                          18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
                          36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
                          54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
                          72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
                          90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
              'xaxis': 'x',
              'y': array([ 0.14506575, -0.67572271, -0.99892136,  2.08816401, -0.3658494 ,
                           0.54200734,  1.24810638,  0.18544457, -0.89016536,  1.87744459,
                           0.95047089, -0.29759266, -0.01780834,  0.09297818,  0.408355  ,
                          -0.33573642, -0.39340552,  0.06241498, -0.03390868,  1.07040321,
                          -0.15762694,  0.33664893, -1.08626924, -0.37079522,  1.67790391,
                           1.83210132,  0.41021522, -0.78251091, -0.18104947,  0.33709152,
                           0.92401579, -0.42456444, -0.76986506, -0.78666594,  0.6445245 ,
                           0.63201785,  0.19736279, -0.44355239, -0.16881329,  0.20726719,
                           0.29949722,  0.60326604,  0.85592445,  0.01332678, -0.79713443,
                           1.0223712 ,  0.14791455, -1.0074221 , -0.79552477,  2.0323054 ,
                           1.85771877,  0.12628584, -0.37694028, -0.75798605,  1.33695997,
                           0.77738904,  0.22040202, -0.37729535,  2.53424302,  0.41694915,
                           0.45102116, -0.60513079, -1.63316094, -0.64953684, -1.4797681 ,
                           0.90953946, -1.60318758,  0.75376491, -0.71316179, -2.17576321,
                          -0.56644947,  0.59829642, -1.90020077,  0.04808401, -0.693024  ,
                          -0.60624577,  0.38622427, -1.21833984, -0.30208282, -0.362618  ,
                          -1.47225121,  1.42969437,  1.68839554, -1.77540492, -1.8547607 ,
                          -1.89348567,  0.80175668,  0.80264571, -0.05044376, -1.30884241,
                          -1.2390902 ,  2.16926557,  0.60622678,  1.24016354, -1.42279253,
                           2.00411457, -2.44114611, -0.51382745, -0.47174677, -0.2478538 ]),
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'hovertemplate': 'variable=B<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'B',
              'marker': {'color': '#EF553B'},
              'name': 'B',
              'offsetgroup': 'B',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
                          18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
                          36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
                          54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
                          72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
                          90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
              'xaxis': 'x',
              'y': array([-1.44655712e+00,  9.72726002e-01, -1.24134971e+00, -3.47269588e-01,
                          -1.98930010e-03,  1.51465990e-01, -1.88631581e+00,  8.34431549e-01,
                          -9.04122671e-02, -2.92617468e-01, -1.09140888e+00,  2.31749627e+00,
                           1.68964087e+00,  1.04171513e+00, -1.07103020e+00,  3.29756341e-01,
                           1.11344636e-01, -5.96000547e-02,  1.11855027e+00,  1.09718149e+00,
                           8.87089607e-01,  1.69334650e+00,  1.21597888e+00,  1.44117684e+00,
                           1.51203667e+00, -3.15675215e-01,  9.87311434e-01, -6.07257105e-01,
                          -1.38805098e+00,  1.00763907e+00,  1.30947806e+00, -5.47399027e-01,
                           7.07942033e-01, -3.70994427e-01,  1.79832931e+00,  1.63970540e+00,
                           8.17643999e-01,  4.92185095e-01,  5.27586719e-01, -1.02509673e-01,
                          -1.30991379e+00,  9.45557814e-02, -3.98362299e-01,  6.40416677e-01,
                           3.76633881e-01,  2.46435541e-01, -2.32722529e+00,  1.65080086e+00,
                           1.80369395e+00,  7.88190408e-01, -8.72279041e-01, -9.16353730e-01,
                          -2.87610466e-01,  1.49119000e+00, -2.27686238e+00, -5.05690294e-01,
                          -1.74155189e+00,  3.54482257e-01, -6.96992553e-01, -6.85582533e-01,
                          -1.33129924e+00,  4.57906095e-01, -6.69966242e-01, -2.34568692e-01,
                           4.54011879e-01, -7.37891410e-01,  6.42415550e-01,  1.83414928e-01,
                          -1.01986521e+00, -1.14294198e+00,  4.75782370e-01, -9.52937883e-02,
                          -8.89158131e-02, -3.69274774e-01,  7.75262378e-01,  4.67883856e-01,
                          -6.87042579e-01,  8.39624870e-01,  5.79733597e-01, -2.41187040e-01,
                           1.37524920e+00,  5.15345831e-01, -6.72060906e-01, -1.41710748e+00,
                          -1.73421291e-01, -6.69558281e-01,  1.20974516e+00,  2.14555233e-01,
                           8.95852100e-01,  1.33424912e+00,  3.55738918e-01,  8.99757019e-01,
                           7.62010717e-04,  1.68224999e+00, -1.04993628e+00,  1.80112328e+00,
                          -2.92413657e+00,  8.12158966e-02,  5.82691502e-01, -2.89114757e-01]),
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'hovertemplate': 'variable=C<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'C',
              'marker': {'color': '#00cc96'},
              'name': 'C',
              'offsetgroup': 'C',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
                          18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
                          36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
                          54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
                          72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
                          90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
              'xaxis': 'x',
              'y': array([ 1.69850709,  0.27069086,  1.12853676, -1.83685214, -1.2763391 ,
                          -0.60487777, -0.21121875, -0.15929351,  0.76146516,  0.03884398,
                          -0.31469836,  1.26781263, -0.14571212,  0.92524889, -0.78686891,
                          -0.37596441,  0.88698573, -0.61889062, -0.65680675, -0.24763572,
                           0.6685243 , -0.05937971,  0.50766336,  0.78631579,  1.55621247,
                           0.28394009,  1.13758868, -0.69324086,  1.56623124,  0.18492399,
                          -0.34223921, -0.50259861,  0.72299857,  0.1801759 , -0.23008824,
                           0.68561897,  0.83846095,  0.57783688, -0.31636708, -0.0324692 ,
                           0.36101766, -0.82819404, -0.55548454, -0.82760685,  1.53580719,
                          -0.06366321,  0.11180289,  0.21906562, -1.01426638,  1.0556654 ,
                           0.73366074, -0.60465835,  0.73943415,  0.77667286, -0.47517776,
                           0.92709415, -0.12645384, -0.21521129, -1.83724353,  0.78882566,
                           0.21587172, -0.17157772,  1.50027605, -1.10875354,  0.64863862,
                          -1.00673828, -1.85278395, -0.7702747 ,  0.2541953 , -2.27332699,
                           1.55276775, -1.03912844, -0.85519959, -1.48671939, -0.36832779,
                          -0.10041821, -1.06109314,  0.21459208, -0.61685018,  1.1168174 ,
                          -1.09579575, -0.11356889,  0.52560154, -1.80472652,  0.83051399,
                          -2.33192067, -0.72245363,  1.00046739, -1.48230876, -0.12747681,
                          -1.07854871,  0.46426378,  0.13339072, -1.79157246,  2.7139953 ,
                          -1.32199221, -0.13419585,  0.01995446,  1.48859986, -1.18550467]),
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'hovertemplate': 'variable=D<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'D',
              'marker': {'color': '#ab63fa'},
              'name': 'D',
              'offsetgroup': 'D',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
                          18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
                          36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
                          54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
                          72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
                          90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
              'xaxis': 'x',
              'y': array([ 0.37224768,  1.42031883,  1.20145859, -0.13710652, -1.24304266,
                          -0.59551599, -0.47443294, -0.44913727,  0.57024184,  1.72277462,
                          -1.96898723, -0.80230027, -0.7119471 ,  0.18782764,  1.23496253,
                           0.49684488,  0.19665696, -0.68659346,  0.98851327, -0.4739083 ,
                          -0.0205633 ,  0.59534879, -1.89123038, -1.63406254,  0.50644479,
                           0.60980649,  0.09218185,  0.39038581,  0.592636  ,  0.54103151,
                          -0.05321278,  0.11695974, -1.0995559 ,  1.0432111 ,  1.57891527,
                          -0.7726653 , -1.49764639, -1.38495994,  0.36118532,  0.59079832,
                           0.93342396, -0.40248614,  0.93116442, -0.77078234,  0.05874043,
                          -2.04532625,  0.02074539, -0.96824628, -2.24102243,  0.4293213 ,
                          -0.66865217, -0.35887624, -0.58456968,  1.07268687, -0.75238089,
                           1.14223055,  1.3963772 , -0.27538684, -0.3590655 ,  1.17721136,
                          -0.84313005,  1.67870319, -0.81276893, -2.56163202, -0.66240228,
                           0.99642798,  0.38578318, -0.1094144 , -1.84387387, -1.4456488 ,
                           1.12830642,  0.11051492, -0.23927836,  1.33369869,  1.36240833,
                          -0.30263702, -1.57534922, -1.43985015,  0.8443372 , -0.76873599,
                          -0.46381107,  2.40341388, -0.7526772 ,  0.2019748 ,  1.30612856,
                           0.28527653, -0.21531036,  1.50493799, -0.09179648,  0.4667109 ,
                          -0.51297486,  0.9846033 ,  0.23060668, -1.14335029, -1.0060148 ,
                          -1.14123362, -1.13696766, -0.60687628,  1.81555913, -1.47814133]),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'variable'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'index'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'value'}}}
})

In [37]:
fig4=px.scatter(df,y='B',x='A')
fig4

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'A=%{x}<br>B=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'symbol': 'circle'},
              'mode': 'markers',
              'name': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'scatter',
              'x': array([ 0.14506575, -0.67572271, -0.99892136,  2.08816401, -0.3658494 ,
                           0.54200734,  1.24810638,  0.18544457, -0.89016536,  1.87744459,
                           0.95047089, -0.29759266, -0.01780834,  0.09297818,  0.408355  ,
                          -0.33573642, -0.39340552,  0.06241498, -0.03390868,  1.07040321,
                          -0.15762694,  0.33664893, -1.08626924, -0.37079522,  1.67790391,
                           1.83210132,  0.41021522, -0.78251091, -0.18104947,  0.33709152,
                           0.92401579, -0.42456444, -0.76986506, -0.78666594,  0.6445245 ,
                           0.63201785,  0.19736279, -0.44355239, -0.16881329,  0.20726719,
                           0.29949722,  0.60326604,  0.85592445,  0.01332678, -0.79713443,
                           1.0223712 ,  0.14791455, -1.0074221 , -0.79552477,  2.0323054 ,
                           1.85771877,  0.12628584, -0.37694028, -0.75798605,  1.33695997,
                           0.77738904,  0.22040202, -0.37729535,  2.53424302,  0.41694915,
                           0.45102116, -0.60513079, -1.63316094, -0.64953684, -1.4797681 ,
                           0.90953946, -1.60318758,  0.75376491, -0.71316179, -2.17576321,
                          -0.56644947,  0.59829642, -1.90020077,  0.04808401, -0.693024  ,
                          -0.60624577,  0.38622427, -1.21833984, -0.30208282, -0.362618  ,
                          -1.47225121,  1.42969437,  1.68839554, -1.77540492, -1.8547607 ,
                          -1.89348567,  0.80175668,  0.80264571, -0.05044376, -1.30884241,
                          -1.2390902 ,  2.16926557,  0.60622678,  1.24016354, -1.42279253,
                           2.00411457, -2.44114611, -0.51382745, -0.47174677, -0.2478538 ]),
              'xaxis': 'x',
              'y': array([-1.44655712e+00,  9.72726002e-01, -1.24134971e+00, -3.47269588e-01,
                          -1.98930010e-03,  1.51465990e-01, -1.88631581e+00,  8.34431549e-01,
                          -9.04122671e-02, -2.92617468e-01, -1.09140888e+00,  2.31749627e+00,
                           1.68964087e+00,  1.04171513e+00, -1.07103020e+00,  3.29756341e-01,
                           1.11344636e-01, -5.96000547e-02,  1.11855027e+00,  1.09718149e+00,
                           8.87089607e-01,  1.69334650e+00,  1.21597888e+00,  1.44117684e+00,
                           1.51203667e+00, -3.15675215e-01,  9.87311434e-01, -6.07257105e-01,
                          -1.38805098e+00,  1.00763907e+00,  1.30947806e+00, -5.47399027e-01,
                           7.07942033e-01, -3.70994427e-01,  1.79832931e+00,  1.63970540e+00,
                           8.17643999e-01,  4.92185095e-01,  5.27586719e-01, -1.02509673e-01,
                          -1.30991379e+00,  9.45557814e-02, -3.98362299e-01,  6.40416677e-01,
                           3.76633881e-01,  2.46435541e-01, -2.32722529e+00,  1.65080086e+00,
                           1.80369395e+00,  7.88190408e-01, -8.72279041e-01, -9.16353730e-01,
                          -2.87610466e-01,  1.49119000e+00, -2.27686238e+00, -5.05690294e-01,
                          -1.74155189e+00,  3.54482257e-01, -6.96992553e-01, -6.85582533e-01,
                          -1.33129924e+00,  4.57906095e-01, -6.69966242e-01, -2.34568692e-01,
                           4.54011879e-01, -7.37891410e-01,  6.42415550e-01,  1.83414928e-01,
                          -1.01986521e+00, -1.14294198e+00,  4.75782370e-01, -9.52937883e-02,
                          -8.89158131e-02, -3.69274774e-01,  7.75262378e-01,  4.67883856e-01,
                          -6.87042579e-01,  8.39624870e-01,  5.79733597e-01, -2.41187040e-01,
                           1.37524920e+00,  5.15345831e-01, -6.72060906e-01, -1.41710748e+00,
                          -1.73421291e-01, -6.69558281e-01,  1.20974516e+00,  2.14555233e-01,
                           8.95852100e-01,  1.33424912e+00,  3.55738918e-01,  8.99757019e-01,
                           7.62010717e-04,  1.68224999e+00, -1.04993628e+00,  1.80112328e+00,
                          -2.92413657e+00,  8.12158966e-02,  5.82691502e-01, -2.89114757e-01]),
              'yaxis': 'y'}],
    'layout': {'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'A'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'B'}}}
})

In [38]:
fig5=px.violin(df)
fig5

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'alignmentgroup': 'True',
              'box': {'visible': False},
              'hovertemplate': 'variable=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa'},
              'name': '',
              'offsetgroup': '',
              'orientation': 'v',
              'scalegroup': 'True',
              'showlegend': False,
              'type': 'violin',
              'x': array(['A', 'A', 'A', ..., 'D', 'D', 'D'], dtype=object),
              'x0': ' ',
              'xaxis': 'x',
              'y': array([ 0.14506575, -0.67572271, -0.99892136, ..., -0.60687628,  1.81555913,
                          -1.47814133]),
              'y0': ' ',
              'yaxis': 'y'}],
    'layout': {'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'violinmode': 'group',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'variable'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'value'}}}
})

In [39]:
fig6=px.bar(df[['A','B']])
fig6

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'alignmentgroup': 'True',
              'hovertemplate': 'variable=A<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'A',
              'marker': {'color': '#636efa'},
              'name': 'A',
              'offsetgroup': 'A',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
                          18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
                          36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
                          54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
                          72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
                          90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
              'xaxis': 'x',
              'y': array([ 0.14506575, -0.67572271, -0.99892136,  2.08816401, -0.3658494 ,
                           0.54200734,  1.24810638,  0.18544457, -0.89016536,  1.87744459,
                           0.95047089, -0.29759266, -0.01780834,  0.09297818,  0.408355  ,
                          -0.33573642, -0.39340552,  0.06241498, -0.03390868,  1.07040321,
                          -0.15762694,  0.33664893, -1.08626924, -0.37079522,  1.67790391,
                           1.83210132,  0.41021522, -0.78251091, -0.18104947,  0.33709152,
                           0.92401579, -0.42456444, -0.76986506, -0.78666594,  0.6445245 ,
                           0.63201785,  0.19736279, -0.44355239, -0.16881329,  0.20726719,
                           0.29949722,  0.60326604,  0.85592445,  0.01332678, -0.79713443,
                           1.0223712 ,  0.14791455, -1.0074221 , -0.79552477,  2.0323054 ,
                           1.85771877,  0.12628584, -0.37694028, -0.75798605,  1.33695997,
                           0.77738904,  0.22040202, -0.37729535,  2.53424302,  0.41694915,
                           0.45102116, -0.60513079, -1.63316094, -0.64953684, -1.4797681 ,
                           0.90953946, -1.60318758,  0.75376491, -0.71316179, -2.17576321,
                          -0.56644947,  0.59829642, -1.90020077,  0.04808401, -0.693024  ,
                          -0.60624577,  0.38622427, -1.21833984, -0.30208282, -0.362618  ,
                          -1.47225121,  1.42969437,  1.68839554, -1.77540492, -1.8547607 ,
                          -1.89348567,  0.80175668,  0.80264571, -0.05044376, -1.30884241,
                          -1.2390902 ,  2.16926557,  0.60622678,  1.24016354, -1.42279253,
                           2.00411457, -2.44114611, -0.51382745, -0.47174677, -0.2478538 ]),
              'yaxis': 'y'},
             {'alignmentgroup': 'True',
              'hovertemplate': 'variable=B<br>index=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': 'B',
              'marker': {'color': '#EF553B'},
              'name': 'B',
              'offsetgroup': 'B',
              'orientation': 'v',
              'showlegend': True,
              'textposition': 'auto',
              'type': 'bar',
              'x': array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
                          18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
                          36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
                          54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71,
                          72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
                          90, 91, 92, 93, 94, 95, 96, 97, 98, 99]),
              'xaxis': 'x',
              'y': array([-1.44655712e+00,  9.72726002e-01, -1.24134971e+00, -3.47269588e-01,
                          -1.98930010e-03,  1.51465990e-01, -1.88631581e+00,  8.34431549e-01,
                          -9.04122671e-02, -2.92617468e-01, -1.09140888e+00,  2.31749627e+00,
                           1.68964087e+00,  1.04171513e+00, -1.07103020e+00,  3.29756341e-01,
                           1.11344636e-01, -5.96000547e-02,  1.11855027e+00,  1.09718149e+00,
                           8.87089607e-01,  1.69334650e+00,  1.21597888e+00,  1.44117684e+00,
                           1.51203667e+00, -3.15675215e-01,  9.87311434e-01, -6.07257105e-01,
                          -1.38805098e+00,  1.00763907e+00,  1.30947806e+00, -5.47399027e-01,
                           7.07942033e-01, -3.70994427e-01,  1.79832931e+00,  1.63970540e+00,
                           8.17643999e-01,  4.92185095e-01,  5.27586719e-01, -1.02509673e-01,
                          -1.30991379e+00,  9.45557814e-02, -3.98362299e-01,  6.40416677e-01,
                           3.76633881e-01,  2.46435541e-01, -2.32722529e+00,  1.65080086e+00,
                           1.80369395e+00,  7.88190408e-01, -8.72279041e-01, -9.16353730e-01,
                          -2.87610466e-01,  1.49119000e+00, -2.27686238e+00, -5.05690294e-01,
                          -1.74155189e+00,  3.54482257e-01, -6.96992553e-01, -6.85582533e-01,
                          -1.33129924e+00,  4.57906095e-01, -6.69966242e-01, -2.34568692e-01,
                           4.54011879e-01, -7.37891410e-01,  6.42415550e-01,  1.83414928e-01,
                          -1.01986521e+00, -1.14294198e+00,  4.75782370e-01, -9.52937883e-02,
                          -8.89158131e-02, -3.69274774e-01,  7.75262378e-01,  4.67883856e-01,
                          -6.87042579e-01,  8.39624870e-01,  5.79733597e-01, -2.41187040e-01,
                           1.37524920e+00,  5.15345831e-01, -6.72060906e-01, -1.41710748e+00,
                          -1.73421291e-01, -6.69558281e-01,  1.20974516e+00,  2.14555233e-01,
                           8.95852100e-01,  1.33424912e+00,  3.55738918e-01,  8.99757019e-01,
                           7.62010717e-04,  1.68224999e+00, -1.04993628e+00,  1.80112328e+00,
                          -2.92413657e+00,  8.12158966e-02,  5.82691502e-01, -2.89114757e-01]),
              'yaxis': 'y'}],
    'layout': {'barmode': 'relative',
               'legend': {'title': {'text': 'variable'}, 'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'index'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'value'}}}
})

In [40]:
px.box(df[['A','B']])

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'alignmentgroup': 'True',
              'hovertemplate': 'variable=%{x}<br>value=%{y}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa'},
              'name': '',
              'notched': False,
              'offsetgroup': '',
              'orientation': 'v',
              'showlegend': False,
              'type': 'box',
              'x': array(['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
                          'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
                          'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
                          'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
                          'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
                          'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
                          'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A',
                          'A', 'A', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
                          'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
                          'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
                          'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
                          'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
                          'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
                          'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'B',
                          'B', 'B', 'B', 'B'], dtype=object),
              'x0': ' ',
              'xaxis': 'x',
              'y': array([ 1.45065752e-01, -6.75722709e-01, -9.98921357e-01,  2.08816401e+00,
                          -3.65849396e-01,  5.42007340e-01,  1.24810638e+00,  1.85444568e-01,
                          -8.90165365e-01,  1.87744459e+00,  9.50470888e-01, -2.97592661e-01,
                          -1.78083362e-02,  9.29781803e-02,  4.08354999e-01, -3.35736419e-01,
                          -3.93405523e-01,  6.24149772e-02, -3.39086827e-02,  1.07040321e+00,
                          -1.57626939e-01,  3.36648935e-01, -1.08626924e+00, -3.70795219e-01,
                           1.67790391e+00,  1.83210132e+00,  4.10215221e-01, -7.82510914e-01,
                          -1.81049466e-01,  3.37091519e-01,  9.24015786e-01, -4.24564443e-01,
                          -7.69865055e-01, -7.86665941e-01,  6.44524501e-01,  6.32017851e-01,
                           1.97362786e-01, -4.43552390e-01, -1.68813288e-01,  2.07267192e-01,
                           2.99497223e-01,  6.03266040e-01,  8.55924452e-01,  1.33267784e-02,
                          -7.97134427e-01,  1.02237120e+00,  1.47914545e-01, -1.00742210e+00,
                          -7.95524772e-01,  2.03230540e+00,  1.85771877e+00,  1.26285840e-01,
                          -3.76940281e-01, -7.57986047e-01,  1.33695997e+00,  7.77389039e-01,
                           2.20402015e-01, -3.77295346e-01,  2.53424302e+00,  4.16949146e-01,
                           4.51021160e-01, -6.05130790e-01, -1.63316094e+00, -6.49536842e-01,
                          -1.47976810e+00,  9.09539459e-01, -1.60318758e+00,  7.53764911e-01,
                          -7.13161789e-01, -2.17576321e+00, -5.66449469e-01,  5.98296421e-01,
                          -1.90020077e+00,  4.80840125e-02, -6.93024005e-01, -6.06245773e-01,
                           3.86224274e-01, -1.21833984e+00, -3.02082820e-01, -3.62618004e-01,
                          -1.47225121e+00,  1.42969437e+00,  1.68839554e+00, -1.77540492e+00,
                          -1.85476070e+00, -1.89348567e+00,  8.01756682e-01,  8.02645714e-01,
                          -5.04437559e-02, -1.30884241e+00, -1.23909020e+00,  2.16926557e+00,
                           6.06226780e-01,  1.24016354e+00, -1.42279253e+00,  2.00411457e+00,
                          -2.44114611e+00, -5.13827453e-01, -4.71746774e-01, -2.47853795e-01,
                          -1.44655712e+00,  9.72726002e-01, -1.24134971e+00, -3.47269588e-01,
                          -1.98930010e-03,  1.51465990e-01, -1.88631581e+00,  8.34431549e-01,
                          -9.04122671e-02, -2.92617468e-01, -1.09140888e+00,  2.31749627e+00,
                           1.68964087e+00,  1.04171513e+00, -1.07103020e+00,  3.29756341e-01,
                           1.11344636e-01, -5.96000547e-02,  1.11855027e+00,  1.09718149e+00,
                           8.87089607e-01,  1.69334650e+00,  1.21597888e+00,  1.44117684e+00,
                           1.51203667e+00, -3.15675215e-01,  9.87311434e-01, -6.07257105e-01,
                          -1.38805098e+00,  1.00763907e+00,  1.30947806e+00, -5.47399027e-01,
                           7.07942033e-01, -3.70994427e-01,  1.79832931e+00,  1.63970540e+00,
                           8.17643999e-01,  4.92185095e-01,  5.27586719e-01, -1.02509673e-01,
                          -1.30991379e+00,  9.45557814e-02, -3.98362299e-01,  6.40416677e-01,
                           3.76633881e-01,  2.46435541e-01, -2.32722529e+00,  1.65080086e+00,
                           1.80369395e+00,  7.88190408e-01, -8.72279041e-01, -9.16353730e-01,
                          -2.87610466e-01,  1.49119000e+00, -2.27686238e+00, -5.05690294e-01,
                          -1.74155189e+00,  3.54482257e-01, -6.96992553e-01, -6.85582533e-01,
                          -1.33129924e+00,  4.57906095e-01, -6.69966242e-01, -2.34568692e-01,
                           4.54011879e-01, -7.37891410e-01,  6.42415550e-01,  1.83414928e-01,
                          -1.01986521e+00, -1.14294198e+00,  4.75782370e-01, -9.52937883e-02,
                          -8.89158131e-02, -3.69274774e-01,  7.75262378e-01,  4.67883856e-01,
                          -6.87042579e-01,  8.39624870e-01,  5.79733597e-01, -2.41187040e-01,
                           1.37524920e+00,  5.15345831e-01, -6.72060906e-01, -1.41710748e+00,
                          -1.73421291e-01, -6.69558281e-01,  1.20974516e+00,  2.14555233e-01,
                           8.95852100e-01,  1.33424912e+00,  3.55738918e-01,  8.99757019e-01,
                           7.62010717e-04,  1.68224999e+00, -1.04993628e+00,  1.80112328e+00,
                          -2.92413657e+00,  8.12158966e-02,  5.82691502e-01, -2.89114757e-01]),
              'y0': ' ',
              'yaxis': 'y'}],
    'layout': {'boxmode': 'group',
               'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 1.0], 'title': {'text': 'variable'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'value'}}}
})

In [41]:
df3=pd.DataFrame({'x':[1,2,3,4],'y':[5,10,15,20],'z':[100,200,300,400]})
df3

   x   y    z
0  1   5  100
1  2  10  200
2  3  15  300
3  4  20  400

In [42]:

fig32fig = px.line_3d(df3, x='x', y='y', z='z')
fig32fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'x=%{x}<br>y=%{y}<br>z=%{z}<extra></extra>',
              'legendgroup': '',
              'line': {'color': '#636efa', 'dash': 'solid'},
              'mode': 'lines',
              'name': '',
              'scene': 'scene',
              'showlegend': False,
              'type': 'scatter3d',
              'x': array([1, 2, 3, 4]),
              'y': array([ 5, 10, 15, 20]),
              'z': array([100, 200, 300, 400])}],
    'layout': {'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'scene': {'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
                         'xaxis': {'title': {'text': 'x'}},
                         'yaxis': {'title': {'text': 'y'}},
                         'zaxis': {'title': {'text': 'z'}}},
               'template': '...'}
})

In [43]:
fig31=px.scatter_3d(df3,x='x',y='y',z='z')
fig31

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'hovertemplate': 'x=%{x}<br>y=%{y}<br>z=%{z}<extra></extra>',
              'legendgroup': '',
              'marker': {'color': '#636efa', 'symbol': 'circle'},
              'mode': 'markers',
              'name': '',
              'scene': 'scene',
              'showlegend': False,
              'type': 'scatter3d',
              'x': array([1, 2, 3, 4]),
              'y': array([ 5, 10, 15, 20]),
              'z': array([100, 200, 300, 400])}],
    'layout': {'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'scene': {'domain': {'x': [0.0, 1.0], 'y': [0.0, 1.0]},
                         'xaxis': {'title': {'text': 'x'}},
                         'yaxis': {'title': {'text': 'y'}},
                         'zaxis': {'title': {'text': 'z'}}},
               'template': '...'}
})

In [44]:
import plotly.graph_objects as go

fig = go.Figure(data=[go.Surface(x=df3['x'], y=df3['y'], z=df3['z'],colorscale='Viridis')])
fig

ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed

Figure({
    'data': [{'colorscale': [[0.0, '#440154'], [0.1111111111111111, '#482878'],
                             [0.2222222222222222, '#3e4989'], [0.3333333333333333,
                             '#31688e'], [0.4444444444444444, '#26828e'],
                             [0.5555555555555556, '#1f9e89'], [0.6666666666666666,
                             '#35b779'], [0.7777777777777778, '#6ece58'],
                             [0.8888888888888888, '#b5de2b'], [1.0, '#fde725']],
              'type': 'surface',
              'x': array([1, 2, 3, 4]),
              'y': array([ 5, 10, 15, 20]),
              'z': array([100, 200, 300, 400])}],
    'layout': {'template': '...'}
})

In [45]:
df

           A         B         C         D
0   0.145066 -1.446557  1.698507  0.372248
1  -0.675723  0.972726  0.270691  1.420319
2  -0.998921 -1.241350  1.128537  1.201459
3   2.088164 -0.347270 -1.836852 -0.137107
4  -0.365849 -0.001989 -1.276339 -1.243043
..       ...       ...       ...       ...
95  2.004115  1.801123 -1.321992 -1.141234
96 -2.441146 -2.924137 -0.134196 -1.136968
97 -0.513827  0.081216  0.019954 -0.606876
98 -0.471747  0.582692  1.488600  1.815559
99 -0.247854 -0.289115 -1.185505 -1.478141

[100 rows x 4 columns]